### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by Jeff17Robbins** [FremyCompany/css-grid-polyfill#20]
Test page at http://jsbin.com/fowawi/1/edit?html,output works on Chrome, and IE9, but not on IE11.

The screenshot attached shows a green rectangle in col2 after first pressing the Step 1 button, and then attempting to hide col2 via its checkbox.  

Expected behavior is for col2 to vanish entirely (works on Chrome and IE9.)  Any changes to the grid element causes things to "get fixed" on IE11 -- pressing the Step 3 button changes its top slightly.  

A more generic fix, which feels like a hack, is to do this:

```javascript
            d = document.createElement('div');
            d1 = grid.appendChild(d);
            grid.removeChild(d1);  
```
(assuming 'grid' has your grid element in it)

This NOOP "change" to the grid element seems to trigger the Mutation Observer that otherwise wasn't fired simply by changing the className classes on the grid element (on IE11.)

![image](https://cloud.githubusercontent.com/assets/2102919/6659182/beb33434-cb55-11e4-952b-af218242e51b.png)

**Comment by FremyCompany** [comment]
Thanks, I'll have a look. I had a very busy week-end and couldn't look at your issue, but I'll try to work on this Wednesday aternoon or next week-end.

**Comment by FremyCompany** [comment]
This bugs looks crazy weird :D

**Comment by FremyCompany** [comment]
Yay, I think I figured it out! 

The DOMUpdateEventStream constructor take a dictionary object with attributes such as { target: HTMLElement, subtree: boolean, attributes: boolean, ... }

For some reason, I once misused it by giving it as argument the target object directly ("document" in that case), which isn't supposed to work (but, in all browsers, this resulted in the HTMLElement being used instead, as "document" has no "target" property, which is what was expected).

However, in IE, the "document" object has a defined "attributes" property (which is null), and "!!null" is equal to "false". As a result, IE was not monitoring attributes changes, and not triggering CSS matching when you changed the className only. The other browsers don't defined the "attributes" property on the document object.

FWIW, it worked in IE9- because MutationObserver isn't implemented there so I use MutationEvents and a completely different code path.

Anyway, fix incoming :D 
:dart:

**Comment by FremyCompany** [comment]
Also, I should use TypeScript.

**Comment by Jeff17Robbins** [comment]
Wow.  Well, nice to know the problem was due to a "pun" like that.  I just
saw a Polymer issue where an anchor element had a "host" attribute and it
messed something up that was assuming "host" meant something special to the
Shadow DOM.  In your case, the pun was inadvertent, and I guess we need to
give IE credit for helping finding it? (Although you did all the work!)
