### ISSUE TITLE
node/browserify support

### ISSUE THREAD

**Issue by bfred-it** [FremyCompany/css-grid-polyfill#27]
What are those `require('a:b')` statements? They don't work in node/browserify. How can I use it with browserify?

**Comment by FremyCompany** [comment]
I've my own build system. Someday I promised I would transform them into "duo.js" requires, but I don't plan to support node as a builder. If you don't need to build the polyfill, you can use the already-built version on https://github.com/FremyCompany/css-grid-polyfill-binaries. Is that a sufficient workaround?

**Comment by bfred-it** [comment]
By not supporting node you're not supporting browserify, which is pretty large chunk of users ([1.8 millions monthly](https://www.npmjs.com/package/browserify)). Besides, you should probably just use ES6 imports at this point, why go with esoteric solutions when there are standards around?

Currently I got around by just using the `.min.js` version, but I have encountered some bugs and trying to fix the code is impossible that way.

**Comment by FremyCompany** [comment]
I'm sympathic to the arguments, but I'm not sure I understand your problem, though.

1. Like most libraries on the web, this project comes in the form of a binary anyone can use. 

2. In addition to this, this project comes with a grunt build that you can run and that will generate a new version of the "min.js" file automatically. It you want to make edits to the source files and see how it helps fix your problem, that should be all you need. But maybe you didn't find out about the grunt build and are wondering how to build? It yes, I should try to make this more obvious...

------------------------------------
 
Moreover, I understand your point about using standards like ES6 Modules but at the time I wrote the project, ES6 module syntax wasn't even finalized; also you'll quickly find out that 'require' isn't compatible with how es6-modules work and I wanted to use something that looked like 'require'.

Now, it I had to start over, I would certainly use something more in line with current practices, but there are thousands of line of code in this project and mv other css polvfills and I already rewrote a huge part of them less than a year ago so I'm not ready to take another shot at this (yet) as I don't feel like I'm preventing people from understanding, modifying and building the code with the solution I’ve right now (don’t forget that refactoring is very time-costly if you want to make sure you didn't break anything in any browser. 

-----------------------------------

If you want the historical reason why I'm currently using a custom build for this project: When I started, I wanted to use grunt to generate documentation files, and when I broke my things into modules, I expanded the existing code with my own require-logic rather than having to maintain a browserify build in addition to a grunt build for the documentation. 

Like I said, I'm sympathic to the idea of using a more standard require code though. I'll make sure to notify you when I come around to this.

**Comment by FremyCompany** [comment]
https://github.com/FremyCompany/css-grid-polyfill/blob/master/README-PARALLIA.md#creating-a-custom-build

**Comment by FremyCompany** [comment]
Just a final note to answer your question. 'xxxx:yyyy' means '%PROJECT_ROOT%/src/xxxx/yyyyy.js'. If you want to try using browserify for the build, it's likely (but not certain) that just updating the paths will do the trick. If it does, that would be interesting to know because then it means it may be easier than expected to migrate.

**Comment by bfred-it** [comment]
Yeah the builder works, for me it's just an extra step but it's okay. Currently though `main` field in package.json is useless since it's not a normal node package. 

---

ES6 modules were totally [finalized a while ago](http://www.2ality.com/2014/09/es6-modules-final.html?m=1). 

Requires and imports still need browserify and/or babel and they are completely interchangeable under these systems, so that isn't a problem either. 

Browserify can be included in the grunt build seamlessly, in a similar fashion to what you're already doing. 

---

Of course I didn't expect you to use ES6 modules two years ago, I was just answering to this:

> Someday I promised I would transform them into "duo.js" requires, but I don't plan to support node as a builder.

If you do transform them, you might as well use a standard. That's what I meant. I think you should be able to do a simple search/replace to transform all the required into node requires. 

If you do that, you can just leave this issue open and reply here. 

---

Thing is that I found this plugin pretty heavy and too automatic for my tastes/necessities. Also there's a nasty bug that causes it to never leave that `for(;;)` loop essentially crashing the tab when I hit some resolutions. You can see that here: http://64.207.183.245 (try resizing the window)

I might just end up replacing it with flexbox or some custom, light script.

**Comment by FremyCompany** [comment]
Okay, I'm finally seeing why you think the build step is annoying. You've your own build step for your website and would like to leverage this one to bundle the polyfill at the same time, instead of as separate process.

Various people will have various build process and I probably can't support them all, but it is likely I could support browserify. I had a look and, by using a "browser" config in package.json, I'm pretty confident I could get something working that makes me satisfied and would be cross-compatible between browserify and my own build system.

I'll keep you tuned, but you can expect some work on this front from me during this week-end.

-------------------------

I can also confirm your other bug and will investigate it. I'll open a new issue for it once I arrive home this evening. To make my life easier, could you possibly replace the "min.js" file you use by the unminified version? That would help me debug the damn thing :-)

**Comment by bfred-it** [comment]
I can't because the non-min file is incompatible with browserify, that's the whole problem. The non-standard require calls make the build fail. The min file has a different variable name for "require()" so that works.

**Comment by FremyCompany** [comment]
Closed by mistake. I meant to close the other bug you mentioned. The plan is still to work on this this weekend.

**Comment by RichiCoder1** [comment]
Meant to throw this in earlier but :+1: to a more standard build process.

**Comment by FremyCompany** [comment]
Could anyone using browserify check that [this branch](https://github.com/FremyCompany/css-grid-polyfill/tree/browserify-support) actually does solve the problem and works as expected?

**Comment by bfred-it** [comment]
I'll definitely test it out tomorrow or on Monday. Thanks!

**Comment by bfred-it** [comment]
It seems to work!

**Comment by FremyCompany** [comment]
Great, I'll merge that when I return home this evening. Thanks for trying out.

**Comment by cesarandreu** [comment]
I just wanna chime in and say that this also works with webpack, although I found it a bit unexpected that the package name is `css-polyfills` instead of `css-grid-polyfill`.

**Comment by FremyCompany** [comment]
This is because I internally have only one project for my two main css polyfills. I will duplicate the package.json file to be able to customize them differently between the two projects, it makes sense.

**Comment by F21** [comment]
I was able to install the `browserify-support` branch using npm like so:

```
npm install git+https://github.com/FremyCompany/css-grid-polyfill.git#browserify-support --save
```

Then it's just a matter of importing it (I am using webpack, so I imported it in my entrypoint file):

```javascript
import 'css-polyfills'
```
