### ISSUE TITLE
Wrong final height for items having height:auto and a replaced/overflow-hidden child element with height as percentage

### ISSUE THREAD

**Issue by Draccoz** [FremyCompany/css-grid-polyfill#39]
Hello. First of all, great job with the polyfill! I love it :D.
Now to the point. I am trying to make a little photo album, but grid-row-end seems to be broken :(. Any way to fix it? Or maybe I am doing something wrong? Here is a link to codepen:
http://codepen.io/Draccoz/pen/dXqKJd

On the right side, top image should take half of the height, just like the bottom ones, but it eats up more. I've set up some z-index'es to make it more visible.
Thanks,
Dracco

**Comment by FremyCompany** [comment]
Hey, that looks like a bug worth fixing.
Based on a quick investigation, the problem looks to be due to the second item that has no "height" declaration applied on it, unlike all the other ones. 

This is the code that reacts differently; though I did not investigate why:
https://github.com/FremyCompany/css-grid-polyfill/blob/master/src/css-grid/lib/grid-layout.js#L2479

The number one supspect is the height:100% declaration, which makes the height of the image depends on the height of the parent element; while the grid has no height, it inherits 0px then suddenly changes once I assigned its height to the grid parent; the decision to include or not an height instructions has already being taken at that point.

I will try to investigate this; but this weekend won't work for me; so that will probably have to wait two weekends looking forward.

Thanks for the bug report!
François

**Comment by Draccoz** [comment]
2 weekends isn't long, I can wait ;). If there is anything I can do to help you, feel free to ask :).

**Comment by FremyCompany** [comment]
I was trying to write a fix for this problem, but that is more difficult than I would like it to be.
In the mean time, here is a workaround: http://codepen.io/FremyCompany/pen/grVKPK (position: absolute set on the image, so that it does not affect the height of the grid item when it has height:auto)

**Comment by Draccoz** [comment]
Works like a charm! Thanks a lot for the time you invest in the project :).

**Comment by FremyCompany** [comment]
I just added the wontfix label because I think what you want is to use the position:absolute thing. A fix would require multiple layout passes because I cannot control this accurately, at least with the set of data I collect currently, so that would require a heavy refactoring and I don't have time to work on that at this point.
