### ISSUE TITLE
Request : grid-gap

### ISSUE THREAD

**Issue by raphaelgoetter** [FremyCompany/css-grid-polyfill#45]
Hello,

It seems that `grid-gap`, `grid-column-gap` and `grid-row-gap` aren't supported in the polyfill. That would be great on IE/Edge.

(Also, the polyfill doesn't work on Android, is it ?)

Have a nice day.

**Comment by npointercbt** [comment]
https://github.com/FremyCompany/css-grid-polyfill/issues/26

**Comment by FremyCompany** [comment]
Yep, the feature is already tracked in another issue. Thanks for pointing this out.

Regarding the other thing you mention, I cannot be sure because I don't have an Android device, but I don't see a reason it wouldn't work on an Android device either. It should work on any browser. 

The truth though is that I cannot commit any time doing investigations on my polyfills at this point, but I will gladly take a deeper look if someone starts looking into what happens and points me in the right direction. If you have more details on what is (not) happening in terms of js execution, please open a new issue for that.
